export const PRODUCT_LIST_START = 'PRODUCT_LIST_START'
export const PRODUCT_LIST_FINISH = 'PRODUCT_LIST_FINISH'

export const PRODUCT_DETAILS_START = 'PRODUCT_DETAILS_START'
export const PRODUCT_DETAILS_FINISH = 'PRODUCT_DETAILS_FINISH'